[package]
name = "extel"
description = "An extended testing library for scaffolding tests as quickly and easily as possible"
authors = ["Jacob Strader <jtstrader851@gmail.com>"]
version = "0.2.2"
edition = "2021"
repository = "https://github.com/jtstrader/extel"
license = "MIT"
keywords = ["testing", "test", "parameterized"]
categories = ["development-tools", "development-tools::testing"]

[features]
parameterized = []

[dependencies]
extel-core = { path = "../extel-core" }
extel-test-macros = { path = "../extel-macros/extel-test" }
extel-category-macros = { path = "../extel-macros/extel-category" }
thiserror = "1.0.49"
