[package]
name = "e2e"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extel = { path = "../extel", features = ["parameterized"] }
thiserror = "1.0.49"
