[package]
name = "xtl-macros"
description = "The xtl proc macros used for metadata generation"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/jtstrader/xtl"
license = "MIT"
keywords = ["testing", "test"]
categories = ["development-tools", "development-tools::testing"]
exclude = ["/tests"]

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
syn = "2.0.106"
proc-macro2 = "1.0.101"
xtl-core = { path = "../xtl-core" }
darling = "0.21.3"
