on: push
name: Build Extel
jobs:
  build_extel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Build extel
        working-directory: ./extel
        run: cargo build --release --all-features

      - name: Test extel
        working-directory: ./extel
        run: cargo test

  build_extel_parameterized:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Build extel_parameterized
        working-directory: ./extel_parameterized
        run: cargo build --release --all-features

      - name: Test extel_parameterized
        working-directory: ./extel_parameterized
        run: cargo test
