on: push
name: Clippy Check
jobs:
  extel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: clippy

      - name: Check extel
        run: cargo clippy --all-features --manifest-path ./extel/Cargo.toml -- -Dwarnings

  extel_parameterized:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: clippy

      - name: Check extel_parameterized
        run: cargo clippy --all-features --manifest-path ./extel_parameterized/Cargo.toml -- -Dwarnings
